[env:adafruit_qtpy_esp32]
platform = espressif32
board = adafruit_qtpy_esp32
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    me-no-dev/ESPAsyncWebServer
    me-no-dev/AsyncTCP
    bblanchon/ArduinoJson
